services:
  frontend:
    build: .
    container_name: recruiting-app-frontend
    ports:
      - "3001:80"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    networks:
      - recruiting-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  recruiting-network:
    driver: bridge
    external: true  # Use existing network from backend

# Build and run with:
# docker compose up --build